apiVersion: v2
name: helm
description: A Helm chart for Kubernetes
type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - alias: carledgerpostgres
    name: postgresql
    version: 16.2.1
    repository: https://charts.bitnami.com/bitnami
  - name: infinispan
    version: 0.4.1
    repository: https://charts.openshift.io/
