ingress:
  className: nginx
  host:
  certManager: lets-encrypt

carLedger:
  replicas: 1
  image:
    repository: ghcr.io/3thr3n/car-ledger
    tag: 12836065350-linux-amd64
  securityContext:
    runAsNonRoot: true
  auth:
    clientId: carLedger
    scopes: "offline_access,email,profile"

carledgerpostgres:
  nameOverride: postgresql
  backup:
    enabled: false
  auth:
    database: "car-ledger"
    existingSecret: car-ledger-postgresql

infinispan:
  deploy:
    expose:
      type: ""
    nameOverride: car-ledger-infinispan
    security:
      secretName: infinispan
