ingress:
  className: nginx
  host:
  certManager:

carLedger:
  replicas: 1
  image:
    repository: ghcr.io/3thr3n/car-ledger
    tag: 97
  securityContext:
    runAsNonRoot: true
  auth:
    url:
    clientId: "carLedger"
    scopes: "offline_access,email,profile"
  infinispan:
    hosts: "car-ledger-infinispan"
  postgres:
    jdbc:
    host: "car-ledger-postgresql"
    port: 5432
    database: car-ledger
    auth:
      username: "postgres"
      secret: "car-ledger-postgresql"
      secretPasswordKey: "adminPostgres"
      secretUsernameKey:

carledgerpostgres:
  enabled: true
  nameOverride: postgresql
  backup:
    enabled: false
  auth:
    database: "car-ledger"
    existingSecret: "car-ledger-postgresql"

infinispan:
  enabled: true
  deploy:
    expose:
      type: ""
    nameOverride: "car-ledger-infinispan"
    security:
      secretName: infinispan
