apiVersion: v1
kind: Service
metadata:
  name: car-ledger-sv
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: access
      name: http
    - port: 9000
      targetPort: management
      name: management
