apiVersion: v1
kind: Service
metadata:
  name: car-ledger-sv
spec:
  selector:
    app: car-ledger
  type: ClusterIP
  ports:
    - port: 80
      targetPort: access
      name: http
    - port: 9000
      targetPort: management
      name: management
