package de.codeflowwizardry.carledger;

import java.time.LocalDate;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.codeflowwizardry.carledger.data.RecurringBillEntity;
import de.codeflowwizardry.carledger.data.RecurringBillPaymentEntity;
import de.codeflowwizardry.carledger.data.repository.RecurringBillPaymentRepository;
import de.codeflowwizardry.carledger.data.repository.RecurringBillRepository;
import io.quarkus.scheduler.Scheduled;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;

@ApplicationScoped
public class ScheduledPayments
{
	private final static Logger LOG = LoggerFactory.getLogger(ScheduledPayments.class);

	private final RecurringBillRepository recurringBillRepository;
	private final RecurringBillPaymentRepository recurringBillPaymentRepository;

	@Inject
	public ScheduledPayments(RecurringBillRepository recurringBillRepository,
			RecurringBillPaymentRepository recurringBillPaymentRepository)
	{
		this.recurringBillRepository = recurringBillRepository;
		this.recurringBillPaymentRepository = recurringBillPaymentRepository;
	}

	@Transactional
	@Scheduled(cron = "0 0 1 * * ?")
	void generateDuePayments()
	{
		recurringBillRepository.listAll().stream()
				.filter(b -> b.getNextDueDate() != null && !b.getNextDueDate().isAfter(LocalDate.now()))
				.forEach(b -> {
					if (createPayment(b))
					{
						b.advance();
						recurringBillRepository.persist(b);
					}
				});
	}

	private boolean createPayment(RecurringBillEntity recurringBillEntity)
	{
		LocalDate nextDueDate = recurringBillEntity.getNextDueDate();

		RecurringBillPaymentEntity rbpe = new RecurringBillPaymentEntity(recurringBillEntity);
		rbpe.setAmount(recurringBillEntity.getAmount());
		rbpe.setAutoGenerated(true);
		rbpe.setPaidDate(nextDueDate);
		rbpe.setDueDate(nextDueDate);

		try
		{
			recurringBillPaymentRepository.persist(rbpe);
		}
		catch (Exception e)
		{
			LOG.error("Could not persist recurring payment");
			return false;
		}
		return true;
	}
}
