apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.infinispan.deploy.security.secretName }}
type: Opaque
stringData:
  username: "infinispan"
  password: "infinispan"
  identities-batch: |-
    user create infinispan -p infinispan -g admin

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.carledgerpostgres.auth.existingSecret }}
type: Opaque
stringData:
  {{ .Values.carledgerpostgres.auth.secretKeys.userPasswordKey }}: "postgres"
  {{ .Values.carledgerpostgres.auth.secretKeys.adminPasswordKey }}: "adminPostgres"
  {{ .Values.carledgerpostgres.auth.secretKeys.replicationPasswordKey }}: "replicaPostgres"