apiVersion: v1
kind: ServiceAccount
metadata:
  name: "car-ledger-sa"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "car-ledger-role"
rules:
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "car-ledger-role-binding"
subjects:
  - kind: ServiceAccount
    name: "car-ledger-sa"
roleRef:
  kind: Role
  name: "car-ledger-role"
  apiGroup: rbac.authorization.k8s.io
