keycloak:
  auth:
    adminUser: car-ledger
    adminPassword: car-ledger
  resourcesPreset: small
  metrics:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    tls: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: lets-encrypt
    hostname: