services:
  keycloak:
    image: bitnami/keycloak:26
    ports:
      - '8085:8080'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
      KEYCLOAK_DATABASE_VENDOR: 'dev-mem'
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    volumes:
      - ./realm.json:/opt/bitnami/keycloak/data/import/realm.json
