package de.codeflowwizardry.carledger.data;

import java.math.BigDecimal;
import java.time.LocalDate;

import jakarta.persistence.*;

@Entity(name = "recurring_bill_payment")
public class RecurringBillPaymentEntity
{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(insertable = false, updatable = false)
	private Long id;

	@ManyToOne(optional = false)
	@JoinColumn(name = "rp_recurring_bill_id")
	private RecurringBillEntity bill;

	@Column(name = "rp_due_date")
	private LocalDate dueDate; // the month this payment belongs to

	@Column(name = "rp_paid_date")
	private LocalDate paidDate; // same as dueDate for auto-generated history

	@Column(name = "rp_amount")
	private BigDecimal amount;

	@Column(name = "rp_auto_generated")
	private boolean autoGenerated;

	public RecurringBillPaymentEntity()
	{
	}

	public RecurringBillPaymentEntity(RecurringBillEntity bill)
	{
		this.bill = bill;
	}

	public Long getId()
	{
		return id;
	}

	public RecurringBillEntity getBill()
	{
		return bill;
	}

	public LocalDate getDueDate()
	{
		return dueDate;
	}

	public void setDueDate(LocalDate dueDate)
	{
		this.dueDate = dueDate;
	}

	public LocalDate getPaidDate()
	{
		return paidDate;
	}

	public void setPaidDate(LocalDate paidDate)
	{
		this.paidDate = paidDate;
	}

	public BigDecimal getAmount()
	{
		return amount;
	}

	public void setAmount(BigDecimal amount)
	{
		this.amount = amount;
	}

	public void setAutoGenerated(boolean autoGenerated)
	{
		this.autoGenerated = autoGenerated;
	}
}
