package de.codeflowwizardry.carledger.data.factory;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import de.codeflowwizardry.carledger.data.CarEntity;
import de.codeflowwizardry.carledger.data.RecurringBillEntity;
import de.codeflowwizardry.carledger.data.RecurringBillPaymentEntity;
import de.codeflowwizardry.carledger.data.repository.CarRepository;
import de.codeflowwizardry.carledger.data.repository.RecurringBillPaymentRepository;
import de.codeflowwizardry.carledger.data.repository.RecurringBillRepository;
import de.codeflowwizardry.carledger.exception.WrongUserException;
import de.codeflowwizardry.carledger.rest.car.recurring.RecurringBillInput;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.transaction.Transactional;
import jakarta.ws.rs.BadRequestException;
import jakarta.ws.rs.core.Response;

@ApplicationScoped
public class RecurringBillFactory
{
	private final RecurringBillRepository recurringBillRepository;
	private final RecurringBillPaymentRepository recurringBillPaymentRepository;
	private final CarRepository carRepository;

	@Inject
	public RecurringBillFactory(RecurringBillRepository recurringBillRepository,
			RecurringBillPaymentRepository recurringBillPaymentRepository, CarRepository carRepository)
	{
		this.recurringBillRepository = recurringBillRepository;
		this.recurringBillPaymentRepository = recurringBillPaymentRepository;
		this.carRepository = carRepository;
	}

	@Transactional
	public RecurringBillEntity create(long carId, RecurringBillInput input, String name)
	{
		List<String> validate = input.validate();
		if (!validate.isEmpty())
		{
			throw new BadRequestException(Response.status(400).entity(validate).build());
		}

		CarEntity car = carRepository.findById(carId, name);

		if (car == null)
		{
			throw new WrongUserException();
		}

		RecurringBillEntity recurringBillEntity = new RecurringBillEntity(car);
		recurringBillEntity.setName(input.name());
		recurringBillEntity.setDescription(input.description());
		recurringBillEntity.setCategory(input.category());
		recurringBillEntity.setInterval(input.billInterval());
		recurringBillEntity.setAmount(input.amount());
		recurringBillEntity.setStartDate(input.startDate());
		recurringBillEntity.setNextDueDate(input.startDate());
		recurringBillEntity.setEndDate(input.endDate());

		List<RecurringBillPaymentEntity> payments = generateHistory(recurringBillEntity);

		BigDecimal total = payments
				.stream()
				.map(RecurringBillPaymentEntity::getAmount)
				.reduce(BigDecimal::add)
				.orElse(BigDecimal.ZERO);

		recurringBillEntity.setTotal(total);

		recurringBillRepository.persist(recurringBillEntity);
		recurringBillPaymentRepository.persist(payments);

		recurringBillEntity.getRecurringBillPaymentEntities().addAll(payments);

		return recurringBillEntity;
	}

	private List<RecurringBillPaymentEntity> generateHistory(RecurringBillEntity bill)
	{
		List<RecurringBillPaymentEntity> payments = new ArrayList<>();
		LocalDate cursor = bill.getStartDate();
		LocalDate today = LocalDate.now();
		LocalDate todayOrEnd = bill.getEndDate() != null ? bill.getEndDate() : today;

		while (cursor.isBefore(todayOrEnd) && cursor.isBefore(today))
		{
			RecurringBillPaymentEntity p = new RecurringBillPaymentEntity(bill);
			p.setDueDate(cursor);
			p.setPaidDate(cursor);
			p.setAmount(bill.getAmount());
			p.setAutoGenerated(true);
			payments.add(p);

			cursor = bill.advance();
		}
		return payments;
	}
}
