/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarIdRouteRouteImport } from './routes/car/$id/route'

const ErrorLazyRouteImport = createFileRoute('/error')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const CarIndexLazyRouteImport = createFileRoute('/car/')()
const CarNewLazyRouteImport = createFileRoute('/car/new')()
const CarIdIndexLazyRouteImport = createFileRoute('/car/$id/')()
const CarIdEditLazyRouteImport = createFileRoute('/car/$id/edit')()
const CarIdFuelAllLazyRouteImport = createFileRoute('/car/$id/fuel/all')()
const CarIdFuelAddLazyRouteImport = createFileRoute('/car/$id/fuel/add')()

const ErrorLazyRoute = ErrorLazyRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CarIndexLazyRoute = CarIndexLazyRouteImport.update({
  id: '/car/',
  path: '/car/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/car/index.lazy').then((d) => d.Route))
const CarNewLazyRoute = CarNewLazyRouteImport.update({
  id: '/car/new',
  path: '/car/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/car/new.lazy').then((d) => d.Route))
const CarIdRouteRoute = CarIdRouteRouteImport.update({
  id: '/car/$id',
  path: '/car/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIdIndexLazyRoute = CarIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() => import('./routes/car/$id/index.lazy').then((d) => d.Route))
const CarIdEditLazyRoute = CarIdEditLazyRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() => import('./routes/car/$id/edit.lazy').then((d) => d.Route))
const CarIdFuelAllLazyRoute = CarIdFuelAllLazyRouteImport.update({
  id: '/fuel/all',
  path: '/fuel/all',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() =>
  import('./routes/car/$id/fuel/all.lazy').then((d) => d.Route),
)
const CarIdFuelAddLazyRoute = CarIdFuelAddLazyRouteImport.update({
  id: '/fuel/add',
  path: '/fuel/add',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() =>
  import('./routes/car/$id/fuel/add.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/car/$id': typeof CarIdRouteRouteWithChildren
  '/car/new': typeof CarNewLazyRoute
  '/car': typeof CarIndexLazyRoute
  '/car/$id/edit': typeof CarIdEditLazyRoute
  '/car/$id/': typeof CarIdIndexLazyRoute
  '/car/$id/fuel/add': typeof CarIdFuelAddLazyRoute
  '/car/$id/fuel/all': typeof CarIdFuelAllLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/car/new': typeof CarNewLazyRoute
  '/car': typeof CarIndexLazyRoute
  '/car/$id/edit': typeof CarIdEditLazyRoute
  '/car/$id': typeof CarIdIndexLazyRoute
  '/car/$id/fuel/add': typeof CarIdFuelAddLazyRoute
  '/car/$id/fuel/all': typeof CarIdFuelAllLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/car/$id': typeof CarIdRouteRouteWithChildren
  '/car/new': typeof CarNewLazyRoute
  '/car/': typeof CarIndexLazyRoute
  '/car/$id/edit': typeof CarIdEditLazyRoute
  '/car/$id/': typeof CarIdIndexLazyRoute
  '/car/$id/fuel/add': typeof CarIdFuelAddLazyRoute
  '/car/$id/fuel/all': typeof CarIdFuelAllLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/error'
    | '/car/$id'
    | '/car/new'
    | '/car'
    | '/car/$id/edit'
    | '/car/$id/'
    | '/car/$id/fuel/add'
    | '/car/$id/fuel/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/error'
    | '/car/new'
    | '/car'
    | '/car/$id/edit'
    | '/car/$id'
    | '/car/$id/fuel/add'
    | '/car/$id/fuel/all'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/error'
    | '/car/$id'
    | '/car/new'
    | '/car/'
    | '/car/$id/edit'
    | '/car/$id/'
    | '/car/$id/fuel/add'
    | '/car/$id/fuel/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ErrorLazyRoute: typeof ErrorLazyRoute
  CarIdRouteRoute: typeof CarIdRouteRouteWithChildren
  CarNewLazyRoute: typeof CarNewLazyRoute
  CarIndexLazyRoute: typeof CarIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/': {
      id: '/car/'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/new': {
      id: '/car/new'
      path: '/car/new'
      fullPath: '/car/new'
      preLoaderRoute: typeof CarNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/$id': {
      id: '/car/$id'
      path: '/car/$id'
      fullPath: '/car/$id'
      preLoaderRoute: typeof CarIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/$id/': {
      id: '/car/$id/'
      path: '/'
      fullPath: '/car/$id/'
      preLoaderRoute: typeof CarIdIndexLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
    '/car/$id/edit': {
      id: '/car/$id/edit'
      path: '/edit'
      fullPath: '/car/$id/edit'
      preLoaderRoute: typeof CarIdEditLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
    '/car/$id/fuel/all': {
      id: '/car/$id/fuel/all'
      path: '/fuel/all'
      fullPath: '/car/$id/fuel/all'
      preLoaderRoute: typeof CarIdFuelAllLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
    '/car/$id/fuel/add': {
      id: '/car/$id/fuel/add'
      path: '/fuel/add'
      fullPath: '/car/$id/fuel/add'
      preLoaderRoute: typeof CarIdFuelAddLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
  }
}

interface CarIdRouteRouteChildren {
  CarIdEditLazyRoute: typeof CarIdEditLazyRoute
  CarIdIndexLazyRoute: typeof CarIdIndexLazyRoute
  CarIdFuelAddLazyRoute: typeof CarIdFuelAddLazyRoute
  CarIdFuelAllLazyRoute: typeof CarIdFuelAllLazyRoute
}

const CarIdRouteRouteChildren: CarIdRouteRouteChildren = {
  CarIdEditLazyRoute: CarIdEditLazyRoute,
  CarIdIndexLazyRoute: CarIdIndexLazyRoute,
  CarIdFuelAddLazyRoute: CarIdFuelAddLazyRoute,
  CarIdFuelAllLazyRoute: CarIdFuelAllLazyRoute,
}

const CarIdRouteRouteWithChildren = CarIdRouteRoute._addFileChildren(
  CarIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ErrorLazyRoute: ErrorLazyRoute,
  CarIdRouteRoute: CarIdRouteRouteWithChildren,
  CarNewLazyRoute: CarNewLazyRoute,
  CarIndexLazyRoute: CarIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
