/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const ErrorLazyRouteImport = createFileRoute('/error')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const CarIndexLazyRouteImport = createFileRoute('/car/')()
const BillIndexLazyRouteImport = createFileRoute('/bill/')()
const BillIdLazyRouteImport = createFileRoute('/bill/$id')()

const ErrorLazyRoute = ErrorLazyRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CarIndexLazyRoute = CarIndexLazyRouteImport.update({
  id: '/car/',
  path: '/car/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/car/index.lazy').then((d) => d.Route))
const BillIndexLazyRoute = BillIndexLazyRouteImport.update({
  id: '/bill/',
  path: '/bill/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bill/index.lazy').then((d) => d.Route))
const BillIdLazyRoute = BillIdLazyRouteImport.update({
  id: '/bill/$id',
  path: '/bill/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bill/$id.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/bill/$id': typeof BillIdLazyRoute
  '/bill': typeof BillIndexLazyRoute
  '/car': typeof CarIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/bill/$id': typeof BillIdLazyRoute
  '/bill': typeof BillIndexLazyRoute
  '/car': typeof CarIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/bill/$id': typeof BillIdLazyRoute
  '/bill/': typeof BillIndexLazyRoute
  '/car/': typeof CarIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/error' | '/bill/$id' | '/bill' | '/car'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/error' | '/bill/$id' | '/bill' | '/car'
  id: '__root__' | '/' | '/about' | '/error' | '/bill/$id' | '/bill/' | '/car/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ErrorLazyRoute: typeof ErrorLazyRoute
  BillIdLazyRoute: typeof BillIdLazyRoute
  BillIndexLazyRoute: typeof BillIndexLazyRoute
  CarIndexLazyRoute: typeof CarIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/': {
      id: '/car/'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill/': {
      id: '/bill/'
      path: '/bill'
      fullPath: '/bill'
      preLoaderRoute: typeof BillIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill/$id': {
      id: '/bill/$id'
      path: '/bill/$id'
      fullPath: '/bill/$id'
      preLoaderRoute: typeof BillIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ErrorLazyRoute: ErrorLazyRoute,
  BillIdLazyRoute: BillIdLazyRoute,
  BillIndexLazyRoute: BillIndexLazyRoute,
  CarIndexLazyRoute: CarIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
