/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DevI18nRouteImport } from './routes/dev/i18n'
import { Route as CarIdRouteRouteImport } from './routes/car/$id/route'

const ErrorLazyRouteImport = createFileRoute('/error')()
const AboutLazyRouteImport = createFileRoute('/about')()
const IndexLazyRouteImport = createFileRoute('/')()
const CarIndexLazyRouteImport = createFileRoute('/car/')()
const Dev404LazyRouteImport = createFileRoute('/dev/404')()
const CarNewLazyRouteImport = createFileRoute('/car/new')()
const CarIdIndexLazyRouteImport = createFileRoute('/car/$id/')()
const CarIdEditLazyRouteImport = createFileRoute('/car/$id/edit')()
const CarIdBillAddLazyRouteImport = createFileRoute('/car/$id/bill/add')()
const CarIdBillFuelIndexLazyRouteImport = createFileRoute(
  '/car/$id/bill/fuel/',
)()

const ErrorLazyRoute = ErrorLazyRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CarIndexLazyRoute = CarIndexLazyRouteImport.update({
  id: '/car/',
  path: '/car/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/car/index.lazy').then((d) => d.Route))
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const Dev404LazyRoute = Dev404LazyRouteImport.update({
  id: '/dev/404',
  path: '/dev/404',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dev/404.lazy').then((d) => d.Route))
const CarNewLazyRoute = CarNewLazyRouteImport.update({
  id: '/car/new',
  path: '/car/new',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/car/new.lazy').then((d) => d.Route))
const DevI18nRoute = DevI18nRouteImport.update({
  id: '/dev/i18n',
  path: '/dev/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIdRouteRoute = CarIdRouteRouteImport.update({
  id: '/car/$id',
  path: '/car/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIdIndexLazyRoute = CarIdIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() => import('./routes/car/$id/index.lazy').then((d) => d.Route))
const CarIdEditLazyRoute = CarIdEditLazyRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() => import('./routes/car/$id/edit.lazy').then((d) => d.Route))
const CarIdBillAddLazyRoute = CarIdBillAddLazyRouteImport.update({
  id: '/bill/add',
  path: '/bill/add',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() =>
  import('./routes/car/$id/bill/add.lazy').then((d) => d.Route),
)
const CarIdBillFuelIndexLazyRoute = CarIdBillFuelIndexLazyRouteImport.update({
  id: '/bill/fuel/',
  path: '/bill/fuel/',
  getParentRoute: () => CarIdRouteRoute,
} as any).lazy(() =>
  import('./routes/car/$id/bill/fuel/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/car/$id': typeof CarIdRouteRouteWithChildren
  '/dev/i18n': typeof DevI18nRoute
  '/car/new': typeof CarNewLazyRoute
  '/dev/404': typeof Dev404LazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/car': typeof CarIndexLazyRoute
  '/car/$id/edit': typeof CarIdEditLazyRoute
  '/car/$id/': typeof CarIdIndexLazyRoute
  '/car/$id/bill/add': typeof CarIdBillAddLazyRoute
  '/car/$id/bill/fuel': typeof CarIdBillFuelIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/dev/i18n': typeof DevI18nRoute
  '/car/new': typeof CarNewLazyRoute
  '/dev/404': typeof Dev404LazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/car': typeof CarIndexLazyRoute
  '/car/$id/edit': typeof CarIdEditLazyRoute
  '/car/$id': typeof CarIdIndexLazyRoute
  '/car/$id/bill/add': typeof CarIdBillAddLazyRoute
  '/car/$id/bill/fuel': typeof CarIdBillFuelIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/error': typeof ErrorLazyRoute
  '/car/$id': typeof CarIdRouteRouteWithChildren
  '/dev/i18n': typeof DevI18nRoute
  '/car/new': typeof CarNewLazyRoute
  '/dev/404': typeof Dev404LazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/car/': typeof CarIndexLazyRoute
  '/car/$id/edit': typeof CarIdEditLazyRoute
  '/car/$id/': typeof CarIdIndexLazyRoute
  '/car/$id/bill/add': typeof CarIdBillAddLazyRoute
  '/car/$id/bill/fuel/': typeof CarIdBillFuelIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/error'
    | '/car/$id'
    | '/dev/i18n'
    | '/car/new'
    | '/dev/404'
    | '/dashboard'
    | '/car'
    | '/car/$id/edit'
    | '/car/$id/'
    | '/car/$id/bill/add'
    | '/car/$id/bill/fuel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/error'
    | '/dev/i18n'
    | '/car/new'
    | '/dev/404'
    | '/dashboard'
    | '/car'
    | '/car/$id/edit'
    | '/car/$id'
    | '/car/$id/bill/add'
    | '/car/$id/bill/fuel'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/error'
    | '/car/$id'
    | '/dev/i18n'
    | '/car/new'
    | '/dev/404'
    | '/dashboard/'
    | '/car/'
    | '/car/$id/edit'
    | '/car/$id/'
    | '/car/$id/bill/add'
    | '/car/$id/bill/fuel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ErrorLazyRoute: typeof ErrorLazyRoute
  CarIdRouteRoute: typeof CarIdRouteRouteWithChildren
  DevI18nRoute: typeof DevI18nRoute
  CarNewLazyRoute: typeof CarNewLazyRoute
  Dev404LazyRoute: typeof Dev404LazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  CarIndexLazyRoute: typeof CarIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/': {
      id: '/car/'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/404': {
      id: '/dev/404'
      path: '/dev/404'
      fullPath: '/dev/404'
      preLoaderRoute: typeof Dev404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/new': {
      id: '/car/new'
      path: '/car/new'
      fullPath: '/car/new'
      preLoaderRoute: typeof CarNewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/i18n': {
      id: '/dev/i18n'
      path: '/dev/i18n'
      fullPath: '/dev/i18n'
      preLoaderRoute: typeof DevI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/$id': {
      id: '/car/$id'
      path: '/car/$id'
      fullPath: '/car/$id'
      preLoaderRoute: typeof CarIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/$id/': {
      id: '/car/$id/'
      path: '/'
      fullPath: '/car/$id/'
      preLoaderRoute: typeof CarIdIndexLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
    '/car/$id/edit': {
      id: '/car/$id/edit'
      path: '/edit'
      fullPath: '/car/$id/edit'
      preLoaderRoute: typeof CarIdEditLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
    '/car/$id/bill/add': {
      id: '/car/$id/bill/add'
      path: '/bill/add'
      fullPath: '/car/$id/bill/add'
      preLoaderRoute: typeof CarIdBillAddLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
    '/car/$id/bill/fuel/': {
      id: '/car/$id/bill/fuel/'
      path: '/bill/fuel'
      fullPath: '/car/$id/bill/fuel'
      preLoaderRoute: typeof CarIdBillFuelIndexLazyRouteImport
      parentRoute: typeof CarIdRouteRoute
    }
  }
}

interface CarIdRouteRouteChildren {
  CarIdEditLazyRoute: typeof CarIdEditLazyRoute
  CarIdIndexLazyRoute: typeof CarIdIndexLazyRoute
  CarIdBillAddLazyRoute: typeof CarIdBillAddLazyRoute
  CarIdBillFuelIndexLazyRoute: typeof CarIdBillFuelIndexLazyRoute
}

const CarIdRouteRouteChildren: CarIdRouteRouteChildren = {
  CarIdEditLazyRoute: CarIdEditLazyRoute,
  CarIdIndexLazyRoute: CarIdIndexLazyRoute,
  CarIdBillAddLazyRoute: CarIdBillAddLazyRoute,
  CarIdBillFuelIndexLazyRoute: CarIdBillFuelIndexLazyRoute,
}

const CarIdRouteRouteWithChildren = CarIdRouteRoute._addFileChildren(
  CarIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ErrorLazyRoute: ErrorLazyRoute,
  CarIdRouteRoute: CarIdRouteRouteWithChildren,
  DevI18nRoute: DevI18nRoute,
  CarNewLazyRoute: CarNewLazyRoute,
  Dev404LazyRoute: Dev404LazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  CarIndexLazyRoute: CarIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
